# Generated by Django 5.0.4 on 2024-04-06 19:48

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('author', models.CharField()),
                ('description', models.TextField()),
                ('api_rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('page_count', models.PositiveIntegerField()),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=4)),
                ('img_url', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Book_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('date_started', models.DateField(default=django.utils.timezone.now, null=True)),
                ('date_finished', models.DateField(default=django.utils.timezone.now, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_ratings', to='book_app.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
