# Generated by Django 5.0.4 on 2024-04-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_alter_book_api_rating_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
